apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - inventory-service.yaml
  - order-service.yaml
  - user-service.yaml
  - product-service.yaml
  - frontend.yaml
  - ingress.yaml
