
---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: ecommerce-app
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: ecommerce-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: ghcr.io/cnd2425/user-service:latest
        env:
          - name: MONGODB_URL
            value: "mongodb+srv://test:test@ecommerce.fgvr9.mongodb.net/store?retryWrites=true&w=majority&appName=ecommerce"
        ports:
        - containerPort: 8080